x-front-base: &front
  build:
    context: .
    target: main
  environment:
    - VITE_PUBLIC_BASE_PATH=${VITE_PUBLIC_BASE_PATH}
  labels:
    - traefik.http.routers.front.rule=PathPrefix(`/`)
    - traefik.http.services.front.loadbalancer.server.port=8080
  ports:
    - 8080:8080

services:
  front:
    <<: *front
    profiles:
      - main
    develop:
      watch:
        - path: .
          action: rebuild

  front_dev:
    <<: *front
    profiles:
      - dev
    build:
      target: dev
    develop:
      watch:
        - path: .
          target: /src
          action: sync
        - path: package.json
          target: /src/package.json
          action: rebuild
          exec:
            command: pnpm i
