services:
  back:
    build:
      context: .
    environment:
      DATA_FOLDER_PATH: /data
      PORT: 8080
    volumes:
      - ${DATA_FOLDER_PATH}:/data
    develop:
      watch:
        - path: .
          include:
            - '**/*.go'
            - go.mod
            - go.sum
          action: rebuild
    labels:
      - traefik.http.routers.back.rule=PathPrefix(`${BASE_PATH}/folders`)
      - traefik.http.routers.back.middlewares=strip_base_path@docker
      - traefik.http.services.back.loadbalancer.server.port=8080
    cap_drop:
      - ALL
    read_only: true

  router:
    image: traefik
    command: --providers.docker
    # command: --providers.docker --accesslog=true --log.level=DEBUG
    ports:
      - ${PORT}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.http.middlewares.strip_base_path.stripprefix.prefixes=${BASE_PATH}

include:
  - frontend/docker-compose.yaml