services:
  fairdrop:
    container_name: fairdrop
    build:
      context: .
      args:
        - BASE_PATH=${BASE_PATH}
    environment:
      DATA_FOLDER_PATH: /data
      PORT: 8080
      BASE_PATH: ${BASE_PATH}
    ports:
      - ${PORT}:8080
    volumes:
      - ${DATA_FOLDER_PATH}:/data
