services:
  back:
    build:
      context: .
    environment:
      DATA_FOLDER_PATH: /data
      PORT: 8080
    # ports:
    #   - ${PORT}:8080
    volumes:
      - ${DATA_FOLDER_PATH}:/data
    develop:
      watch:
        - path: .
          include:
            - '*.go'
            - go.mod
            - go.sum
          action: rebuild
    labels:
      - traefik.http.routers.back.rule=PathPrefix(`/folders`)
      - traefik.http.services.back.loadbalancer.server.port=8080

  router:
    image: traefik
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

include:
  - frontend/docker-compose.yaml